### PR TITLE
[WIP] add testcase for describe-level pending string only

### PR DESCRIPTION
**Pull request by Tieske**
When a `pending` entry is added on a describe level, then it will get lost if it doesn't have a function argument.

The added test shows the behaviour, but I haven't been able to add a fix, because of the way the code is structured (heavily event based).

Any help would be appreciated.

### CODE REVIEW

**Comment by DorianGray** [comment]
What needs to be done here?

**Comment by Tieske** [comment]
a hint how to fix this?

**Comment by DorianGray** [comment]
I'll try to refamiliarize myself with the code and get back with a fix then.

**Comment by blueyed** [comment]
It works like this:
```diff
diff --git i/spec/cl_pending.lua w/spec/cl_pending.lua
index 00fa725..8f6938e 100644
--- i/spec/cl_pending.lua
+++ w/spec/cl_pending.lua
@@ -12,5 +12,9 @@ describe('Tests the busted pending functions through the commandline>
       error('this should not run')
     end)
   end)
+
+  local it = pending(' (pending_reason)')
+  it('is made pending', function()
+    assert(false)
+  end)
 end)
-
diff --git i/spec/cl_spec.lua w/spec/cl_spec.lua
index ff3929c..33e4e46 100644
--- i/spec/cl_spec.lua
+++ w/spec/cl_spec.lua
@@ -564,8 +564,8 @@ describe('Tests pending through the commandline', function()
     local line1 = result:match('.-\n')
     local _, pendingDots = line1:gsub('%.', '')
     local _, numPending = result:gsub('Pending %-> .-\n', '')
-    assert.is_equal(2, pendingDots)
-    assert.is_equal(2, numPending)
+    assert.is_equal(3, pendingDots)
+    assert.is_equal(3, numPending)
   end)

   it('--suppress-pending option is honored', function()
```

The reason is that without a `fn` argument it returns the publish function itself: https://github.com/Olivine-Labs/busted/blob/8bbf64d4fa5fc8ba2cd67783da9f045b29c49764/busted/core.lua#L275

See also https://github.com/Olivine-Labs/busted/issues/610#issuecomment-543256635.

**Comment by Tieske** [comment]
replaced by #636

**Pull request closed without merging**
