### PR TITLE
Arrow output character is not ascii

### PR DESCRIPTION
**Pull request by nehz**
In windows 7 (not utf8 console), the arrow character appears as random letters.
Changed arrow character to ascii characters.

### CODE REVIEW

**Comment by DorianGray** [comment]
Not sure why this has failing tests...

**Comment by o-lim** [comment]
Some of the tests check the output strings.  If `→` changed to `=>`, then it would also have to be updated in the tests that are looking for `Error →` or `Pending →`.

**Comment by nehz** [comment]
Yeah I can see for example in:
https://github.com/Olivine-Labs/busted/blob/master/spec/cl_spec.lua
`local _, numErrors = result:gsub('Error → .-\n','')`

Is it ok to go and change these test cases?

**Comment by o-lim** [comment]
Yes, you should change the test to match so that they pass.

What do you think of using `->` for the arrow, to more closely match the single arrow `→` (versus `=>` matching `⇒`)?

**Comment by nehz** [comment]
Changed to `->`. Updated tests.

**Pull request merged**
