### PR TITLE
Update TAP output handler

### LINKED ISSUE #345: Provide more information to testEnd.
I'd like to provide a bit more information than just the stack trace when something fails in the TAP and junit output.  Unfortunately, it seems the nice error message about the failure isn't present until the end of the suite.  Is there any chance this information can be added to the `element` node in the `testEnd` handlers?  I'd do this myself, but I'm still learning lua and busted is quite abstract.

### PR DESCRIPTION
**Pull request by o-lim**
This updates the TAP output handler to output the result of each test as it completes, instead of displaying all test results at the end of a suite. Also update TAP output to report skipped tests and errors occurring outside of tests.
```
$ busted -o TAP
ok 1 - Tests success1
ok 2 - Tests success2
not ok 3 - Tests failure1
# spec/test_spec.lua @ 12
# Failure message: spec/test_spec.lua:13: always fails
not ok 4 - Tests failure2
# spec/test_spec.lua @ 16
# Failure message: spec/test_spec.lua:17: always fails
not ok 5 - Tests error1
# spec/test_spec.lua @ 20
# Failure message: spec/test_spec.lua:21: always throws
not ok 6 - Tests error2
# spec/test_spec.lua @ 24
# Failure message: spec/test_spec.lua:25: always throws
ok 7 - # SKIP Tests pending1
ok 8 - # SKIP spec/test_spec.lua:32: pending2
not ok 9 - Tests teardown
# spec/test_spec.lua @ 2
# Failure message: spec/test_spec.lua:3: error in teardown
1..9
```
```
$ busted -v -o TAP
ok 1 - Tests success1
ok 2 - Tests success2
not ok 3 - Tests failure1
# spec/test_spec.lua @ 12
# Failure message: spec/test_spec.lua:13: always fails
# stack traceback:
#       spec/test_spec.lua:13: in function <spec/test_spec.lua:12>
#
not ok 4 - Tests failure2
# spec/test_spec.lua @ 16
# Failure message: spec/test_spec.lua:17: always fails
# stack traceback:
#       spec/test_spec.lua:17: in function <spec/test_spec.lua:16>
#
not ok 5 - Tests error1
# spec/test_spec.lua @ 20
# Failure message: spec/test_spec.lua:21: always throws
# stack traceback:
#       spec/test_spec.lua:21: in function <spec/test_spec.lua:20>
#
not ok 6 - Tests error2
# spec/test_spec.lua @ 24
# Failure message: spec/test_spec.lua:25: always throws
# stack traceback:
#       spec/test_spec.lua:25: in function <spec/test_spec.lua:24>
#
ok 7 - # SKIP Tests pending1
ok 8 - # SKIP spec/test_spec.lua:32: pending2
not ok 9 - Tests teardown
# spec/test_spec.lua @ 2
# Failure message: spec/test_spec.lua:3: error in teardown
# stack traceback:
#       spec/test_spec.lua:3: in function <spec/test_spec.lua:2>
#
1..9
```

This should fix #345 and helps with #375.

### CODE REVIEW

**Comment by tarruda** [comment]
:+1: 

I have a suggestion: Print the test name before it is executed and a status string after, something along these lines:

Before: 
```
some test ..
```

After:

```
some test .. {ok/fail/pending/error}
```

A possibility is to refactor utfTerminal/plainTerminal to allow subclasses that override the event handlers. I Neovim I have added [this one](https://github.com/neovim/neovim/blob/master/third-party/utfTerminalDetailed.lua), but it could be improved if it was possible to override the "test end" event handler to print a text string instead of a symbol.

**Comment by tarruda** [comment]
BTW here's [utfTerminalDetailed](https://github.com/tarruda/neovim/blob/improve-functional-test-debuggability/third-party/utfTerminalDetailed.lua) updated to the latest busted version

**Comment by jszakmeister** [comment]
> Before:
> 
> some test ..
> After:
> 
> some test .. {ok/fail/pending/error}

That would be nice, but anything that prints to the screen would break parsing the results, and this isn't compatible with [TAP](https://testanything.org/tap-specification.html).  I think it would be better to do:

```text
# some test
ok 1 - some test
# some other test
ok 2 - some other test # SKIP
# another test
not ok 3 - another test
1..3
```

I'd only print the extra `#` lines in verbose mode too.

**Comment by tarruda** [comment]
> That would be nice, but anything that prints to the screen would break parsing the results, and this isn't compatible with TAP.

True, I wasn't considering compatibility with TAP parsers.

In any case I think it would be nice having something like utfTerminalDetailed in busted, it greatly simplifies finding hangs/crashes in tests

**Comment by jszakmeister** [comment]
> In any case I think it would be nice having something like utfTerminalDetailed in busted, it greatly simplifies finding hangs/crashes in tests

A huge :+1:.  I've been looking at similar things with TAP for the same reasons.

**Comment by o-lim** [comment]
Instead of trying to modify the TAP output to do something it was never really designed to do, I created a another output handler that mirrors the gtest unit test output format in PR #394.

**Comment by jszakmeister** [comment]
> Instead of trying to modify the TAP output to do something it was never really designed to do, I created a another output handler that mirrors the gtest unit test output format in PR #394.

I wouldn't say that.  TAP is quite flexible and I've seen it used in interesting ways.  Plus, it's standard format is understood by many tools (part of my motivation in seeing it improved).  I think the small difference here would be to get this line:

```# spec/test_spec.lua @ 12
```

emitted before running the test so that the user has a clue about what's going on.  I've had something fairly close for a while, but getting a better stack trace on failure has been problematic.

**Comment by o-lim** [comment]
Updated to print test name including file and line number with verbose option.

**Comment by o-lim** [comment]
@jszakmeister: Does this work for you?

**Comment by jszakmeister** [comment]
It looks good to me!  I ran across a bug between QuickBuild and this output, but I think it's QB's fault (TAP support is relatively new in QB).

**Comment by jszakmeister** [comment]
@o-lim Do you need anything else from me?

**Comment by tarruda** [comment]
> @o-lim Do you need anything else from me?

I guess he doesn't have commit access and is just waiting for the PR to be merged.

**Comment by jszakmeister** [comment]
With all the work he has done, I just assumed he did. :-)

**Pull request merged**
