### PR TITLE
Use a Lua C module for time related functions

### LINKED ISSUE #472: Remove luasocket dependency
I'm trying to use busted to test code that does different things depending on whether luasocket is installed or not. The luasocket dependency is quite large; and only used for `socket.gettime()` (which returns the current time with microsecond precision)

### PR DESCRIPTION
**Pull request by o-lim**
This removes the dependency on luasocket by adding a C function for `gettime`, instead of using `socket.gettime`. Basically, extracting the time related functions from luasocket and using them to create a Lua C module for busted.

This should resolve #472.

### CODE REVIEW

**Comment by Tieske** [comment]
bad idea... introducing c code into busted.

If using this, then it should be an external module. And then, it would probably be better to think what other very common elements are missing in the lua eco-system and build one lib for that. (eg. randomization, time, copy files iirc)

**Comment by DorianGray** [comment]
I agree, we should definitely pull this out into a separate module. We also need to verify that it works on arm, and x86 32 + 64bit with optimally mips included also.

**Comment by o-lim** [comment]
Sounds good to me.  What would you want to call it and where would you put it?  The code was basically copied from luasocket, so it should work everywhere luasocket works.

**Comment by DorianGray** [comment]
cool, we can drop it in the OL repo if you'd like, or keep it on your local if you want to. It just needs to be available on luarocks.

**Comment by DorianGray** [comment]
You should probably have push access anyways

**Comment by o-lim** [comment]
Dropping it into the OL repo sounds good to me.  It's a really small module, so it shouldn't need much maintenance.

**Comment by o-lim** [comment]
I created a repo for the `gettime` function https://github.com/o-lim/luasystem.  It just provides `gettime` and `sleep` functions as a Lua C module.  I didn't know what to call it so I just named it `luasystem`.  If you don't like the name I can rename it to something else.  And if you guys are okay with everything in it, I can make an initial release and push it to luarocks, then update this PR to use it.

**Comment by DorianGray** [comment]
Very nice! It looks great and is exactly what we need.

**Comment by o-lim** [comment]
Closing this PR and replacing with #488, which uses luasystem to replace luasocket.

**Comment by daurnimator** [comment]
Hmm. I actually would have preferred this going into busted.
Now we just have another C module >.<

**Comment by xpol** [comment]
I'd really glad to see luasocket be removed. It takes too much time to install in ci infrastructure like travis.

**Pull request closed without merging**
