### PR TITLE
Update website with description of standalone mode

### PR DESCRIPTION
**Pull request by o-lim**
Add section on running in standalone mode.

### CODE REVIEW

**Comment by ajacksified** [comment]
> Remove rc rev from version number

Not so sure about that one.

**Comment by o-lim** [comment]
Rebased to bump rev to rc9

**Comment by o-lim** [comment]
If you are going to cut a new release soon, I can bump the rev to rc10 if you prefer.

**Comment by ajacksified** [comment]
Yeah, might as well.

**Comment by o-lim** [comment]
Ok, I bumped the rev to rc10

**Pull request merged**
